import { PropFirm, Offer, Review } from './types';

export const MOCK_FIRMS: PropFirm[] = [
  {
    id: '1',
    name: 'Alpha Capital',
    logo: 'https://alphacapitalgroup.uk/static/media/companyLogoInitials.879d8bbc8b528b1fd27761f4e43c34a0.svg',
    rating: 4.8,
    reviewCount: 1240,
    trustScore: 98,
    maxFunding: 200000,
    profitSplit: '80% - 90%',
    drawdown: '10%',
    price: 499,
    minDays: 0,
    phaseCount: 2,
    tags: ['Forex', 'Crypto', 'Instant'],
    description: 'Leading industry prop firm with instant funding options and high trust score.',
    founded: 2021,
    platforms: ['MT4', 'MT5', 'cTrader']
  },
  {
    id: '2',
    name: 'Blue Guardian',
    logo: 'https://cdn.prod.website-files.com/67d98b7861a3fdabba993d7d/67d98b7961a3fdabba993db4_Logo%20(74).avif',
    rating: 4.6,
    reviewCount: 850,
    trustScore: 92,
    maxFunding: 400000,
    profitSplit: '85%',
    drawdown: '8%',
    price: 299,
    minDays: 5,
    phaseCount: 1,
    tags: ['Forex', 'No Time Limit'],
    description: 'Guardian of your capital. Low spreads and high leverage accounts available.',
    founded: 2019,
    platforms: ['MT4', 'MT5']
  },
  {
    id: '3',
    name: 'FundedNext',
    logo: 'https://fundednext.com/_next/image?url=https%3A%2F%2Fdirslur24ie1a.cloudfront.net%2Ffundednext%2FFundedNext_Logo_White_Christmas_2025.png&w=384&q=75',
    rating: 4.9,
    reviewCount: 3200,
    trustScore: 99,
    maxFunding: 300000,
    profitSplit: 'Up to 95%',
    drawdown: '12%',
    price: 549,
    minDays: 0,
    phaseCount: 2,
    tags: ['Forex', 'Futures', 'Fast Payout'],
    description: 'Get funded and paid within 24 hours. The fastest growing firm in 2024.',
    founded: 2022,
    platforms: ['MT4', 'MT5', 'TradeLocker']
  },
  {
    id: '4',
    name: 'FundingPips',
    logo: 'https://www.fundingpips.com/_next/image?url=%2Fimgs%2Ffp-logo-xms.png&w=384&q=75&dpl=dpl_FYvbqGZXv69q1sK5yL6gLsnh7uSr',
    rating: 4.7,
    reviewCount: 950,
    trustScore: 95,
    maxFunding: 100000,
    profitSplit: '80% - 90%',
    drawdown: '10%',
    price: 139,
    minDays: 5,
    phaseCount: 2,
    tags: ['Cheap', 'High Frequency'],
    description: 'One of the most affordable options in the market with reliable payouts.',
    founded: 2022,
    platforms: ['MT5', 'cTrader']
  },
  {
    id: '5',
    name: 'Goat Funded Trader',
    logo: 'https://cdn.prod.website-files.com/67b3682cc0f1f956e16efe80/67b3682cc0f1f956e16efe99_Logo%20(76).avif',
    rating: 4.5,
    reviewCount: 420,
    trustScore: 89,
    maxFunding: 200000,
    profitSplit: 'Up to 95%',
    drawdown: '8% - 10%',
    price: 189,
    minDays: 0,
    phaseCount: 1,
    tags: ['No Time Limit', 'High Leverage'],
    description: 'A firm built for serious traders with excellent scaling plans.',
    founded: 2023,
    platforms: ['MT4', 'MT5']
  },
  {
    id: '6',
    name: 'The 5ers',
    logo: 'https://the5ers.com/wp-content/uploads/2025/09/5erslogo.svg',
    rating: 4.8,
    reviewCount: 2100,
    trustScore: 97,
    maxFunding: 4000000,
    profitSplit: '50% - 100%',
    drawdown: '6% - 10%',
    price: 260,
    minDays: 0,
    phaseCount: 1,
    tags: ['Forex', 'Instant Funding', 'Growth'],
    description: 'Unique instant funding model and high-stakes accounts for career traders.',
    founded: 2016,
    platforms: ['MT5']
  },
  {
    id: '7',
    name: 'E8 Markets',
    logo: 'https://e8markets.com/images/logo/logo.svg',
    rating: 4.7,
    reviewCount: 1500,
    trustScore: 96,
    maxFunding: 300000,
    profitSplit: '80%',
    drawdown: '8%',
    price: 228,
    minDays: 0,
    phaseCount: 2,
    tags: ['Forex', 'Crypto', 'User Friendly'],
    description: 'Data-driven prop firm with a user-friendly dashboard and clear objectives.',
    founded: 2021,
    platforms: ['MT4', 'MT5']
  },
  {
    id: '8',
    name: 'Blueberry Funded',
    logo: 'https://blueberryfunded.com/wp-content/themes/blueberryfunded-xmas/assets/img/logo.svg',
    rating: 4.6,
    reviewCount: 300,
    trustScore: 93,
    maxFunding: 200000,
    profitSplit: '80% - 90%',
    drawdown: '10%',
    price: 450,
    minDays: 5,
    phaseCount: 2,
    tags: ['Forex', 'New', 'Reliable'],
    description: 'Backed by a major broker group, offering institutional-grade trading conditions.',
    founded: 2023,
    platforms: ['MT4', 'MT5']
  },
  {
    id: '9',
    name: 'Bright Funded',
    logo: 'https://framerusercontent.com/images/N05Mx74TjAO6yL26feYmEJQo3Ww.png?width=64&height=64',
    rating: 4.5,
    reviewCount: 180,
    trustScore: 90,
    maxFunding: 100000,
    profitSplit: '80%',
    drawdown: '10%',
    price: 150,
    minDays: 0,
    phaseCount: 2,
    tags: ['Crypto', 'High Leverage'],
    description: 'Specialized in crypto trading with competitive spreads and high leverage.',
    founded: 2023,
    platforms: ['MT5', 'TradeLocker']
  },
  {
    id: '10',
    name: 'Aqua Funded',
    logo: 'https://cdn.prod.website-files.com/68b69f4a2b57f5b22e3f9954/68b69f4a2b57f5b22e3f9998_8f1052d21ee2f1aa837a6d91c0accb63_Brand%20TypeWhite.svg',
    rating: 4.4,
    reviewCount: 250,
    trustScore: 88,
    maxFunding: 200000,
    profitSplit: '90%',
    drawdown: '8%',
    price: 199,
    minDays: 0,
    phaseCount: 2,
    tags: ['Forex', 'Fast Payout'],
    description: 'Superior trading conditions with raw spreads and fast execution.',
    founded: 2023,
    platforms: ['MT4', 'MT5']
  },
  {
    id: '11',
    name: 'Think Capital',
    logo: 'https://placehold.co/400x100/121212/FFFFFF/png?text=Think+Capital',
    rating: 4.3,
    reviewCount: 120,
    trustScore: 85,
    maxFunding: 100000,
    profitSplit: '80%',
    drawdown: '10%',
    price: 149,
    minDays: 5,
    phaseCount: 2,
    tags: ['Forex', 'Indices'],
    description: 'Modern prop firm focusing on technology and trader education.',
    founded: 2023,
    platforms: ['MT5']
  }
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: '1',
    firmId: '1',
    firmName: 'Alpha Capital',
    logo: 'https://alphacapitalgroup.uk/static/media/companyLogoInitials.879d8bbc8b528b1fd27761f4e43c34a0.svg',
    discount: '20% OFF',
    code: 'MATCH20',
    expiry: '2 days left',
    description: 'Get 20% off all 100k and 200k evaluation accounts.'
  },
  {
    id: '2',
    firmId: '3',
    firmName: 'FundedNext',
    logo: 'https://fundednext.com/_next/image?url=https%3A%2F%2Fdirslur24ie1a.cloudfront.net%2Ffundednext%2FFundedNext_Logo_White_Christmas_2025.png&w=384&q=75',
    discount: '125% Refund',
    code: 'PROFIT125',
    expiry: 'Limited Time',
    description: '125% fee refund with first payout on Stellar accounts.'
  },
  {
    id: '3',
    firmId: '2',
    firmName: 'Blue Guardian',
    logo: 'https://cdn.prod.website-files.com/67d98b7861a3fdabba993d7d/67d98b7961a3fdabba993db4_Logo%20(74).avif',
    discount: 'Buy 1 Get 1',
    code: 'BOGO50',
    expiry: 'Ends Tonight',
    description: 'Buy a 50k account, get a 10k account for free.'
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '101',
    firmId: '1',
    user: 'TraderJoe_99',
    rating: 5,
    date: '2023-10-15',
    content: 'Got my first payout yesterday. Process took about 24 hours. Verification was smooth.',
    verified: true
  },
  {
    id: '102',
    firmId: '1',
    user: 'SarahForex',
    rating: 4,
    date: '2023-10-10',
    content: 'Great spreads, but the dashboard could use some UI updates. Support is responsive.',
    verified: true
  },
  {
    id: '103',
    firmId: '3',
    user: 'ScalpMaster',
    rating: 5,
    date: '2023-09-28',
    content: 'Love the raw spreads. No slippage during news events which is rare.',
    verified: true
  }
];
